Explanation of project.

In [4]:
#import relevant packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [5]:
#read in CSV
df = pd.read_csv('eda_data.csv', index_col=0)

#ensure all columns are displayed throughout exploration
pd.set_option('display.max_columns', None)

In [6]:
df.head()

,Sale Date,Item Name,Quantity,Price,Coupon Code,Coupon Details,Discount Amount,Delivery Discount,Order Delivery,Order Sales Tax,Item Total,Transaction ID,Listing ID,Date Paid,Date Posted,Delivery City,Delivery State,Delivery Country,Order ID,Variations,Number of Items,Order Value,Delivery,Sales tax,Order total,Card Processing Fees,Order Net,Buyer First Name,Has Account
0,12/14/2020,Shiba Inu Postcard,1,3.49,NaN,NaN,0.0,0.0,0.00,0.0,3.49,2227408105,848160656,12/14/2020,12/14/2020,Llanberis,NaN,United Kingdom,1891056637,Colour:Orange,1,3.49,0.00,0.0,3.49,0.34,3.15,tom,1
1,12/13/2020,Age Modifier Card,1,3.99,NaN,NaN,0.0,0.0,0.00,0.0,3.99,2225674913,770402384,12/13/2020,12/14/2020,Reading,NaN,United Kingdom,1889715983,NaN,1,3.99,0.00,0.0,3.99,0.36,3.63,amy,1
2,12/13/2020,Christmas Card,1,3.99,NaN,NaN,0.0,0.0,0.00,0.0,3.99,2215547206,906266421,12/13/2020,12/14/2020,Milton Keynes,NaN,United Kingdom,1880937184,NaN,1,3.99,0.00,0.0,3.99,0.36,3.63,maddie,1
3,12/13/2020,Age Modifier Card,1,3.99,NaN,NaN,0.0,0.0,0.99,0.0,3.99,2225077741,770402384,12/13/2020,12/14/2020,West Warwick,RI,United States,1889252173,NaN,1,3.99,0.99,0.0,5.33,0.41,4.57,rebecca,1
4,12/12/2020,Christmas Card,1,3.99,NaN,NaN,0.0,0.0,0.00,0.0,3.99,2223881739,906266421,12/12/2020,12/14/2020,Hebden Bridge,West Yorkshire,United Kingdom,1888329563,NaN,3,11.97,0.00,0.0,11.97,0.68,11.29,rory,1

## Exploration Structure

Now that we've uploaded our cleaned data, we'll want to explore the data further while continuing to clean the dataframe. We'll take the following steps:

### Initial Exploration

* Look at the dtypes of the columns and convert where appropriate
* Describe the numeric columns 
* Look at the distribution of NaNs and drop where appropriate
* Drop the 'Listing ID' column since it's repeating the info in the 'item name' column
* Drop the 'Date Paid' column since it is the same as the 'Sale Date' column 

-Value counts of columns 
-Bar charts of 'has ccounts', '